
import {recommendModels, recommendDatasets, buildManifest} from "./recommender-core.mjs";
import {models, datasets} from "../data/catalog.mjs";

const $ = id => document.getElementById(id);
const form = $("task-form");

const presets = {
  cylinder: {problem:"cylinder_wake",task_type:"forecasting",dimension:2,mesh_type:"structured",temporal_mode:"autoregressive",geometry_mode:"fixed",physics:"incompressible_navier_stokes",memory:24,requires_long_rollout:true},
  vehicle: {problem:"3d_vehicle_aerodynamics",task_type:"surrogate",dimension:3,mesh_type:"point_cloud",temporal_mode:"steady",geometry_mode:"varying",physics:"aerodynamics",memory:80,requires_geometry_transfer:true,requires_mesh_transfer:true},
  acceleration: {problem:"unsteady_3d_cfd_acceleration",task_type:"acceleration",dimension:3,mesh_type:"unstructured",temporal_mode:"autoregressive",geometry_mode:"varying",physics:"incompressible_navier_stokes",memory:80,requires_conservation:true,requires_long_rollout:true,requires_geometry_transfer:true},
  multiphase: {problem:"particle_multiphase_flow",task_type:"surrogate",dimension:3,mesh_type:"particle",temporal_mode:"autoregressive",geometry_mode:"fixed",physics:"granular",memory:48,requires_conservation:true,requires_long_rollout:true},
  inverse: {problem:"sparse_flow_reconstruction",task_type:"inverse",dimension:2,mesh_type:"structured",temporal_mode:"unsteady",geometry_mode:"fixed",physics:"fluid_dynamics",memory:24,requires_uncertainty:true}
};

function taskFromForm() {
  return {
    problem: $("problem").value.trim(),
    task_type: $("task_type").value,
    dimension: Number($("dimension").value),
    mesh_type: $("mesh_type").value,
    temporal_mode: $("temporal_mode").value,
    geometry_mode: $("geometry_mode").value,
    physics: [$("physics").value],
    fidelity: "unknown",
    requires_conservation: $("requires_conservation").checked,
    requires_uncertainty: $("requires_uncertainty").checked,
    requires_geometry_transfer: $("requires_geometry_transfer").checked,
    requires_mesh_transfer: $("requires_mesh_transfer").checked,
    requires_long_rollout: $("requires_long_rollout").checked,
    hardware_memory_gb: Number($("memory").value) || null,
    preferred_framework: $("framework").value || null,
    notes: "Generated by the NAVIER-CFD browser recommender."
  };
}

function applyPreset(preset) {
  const p = presets[preset];
  if (!p) return;
  for (const [key,value] of Object.entries(p)) {
    const el = $(key);
    if (!el) continue;
    if (el.type === "checkbox") el.checked = Boolean(value);
    else el.value = value;
  }
  for (const id of ["requires_conservation","requires_uncertainty","requires_geometry_transfer","requires_mesh_transfer","requires_long_rollout"]) {
    if (!(id in p)) $(id).checked = false;
  }
  run();
}

function tag(text){ return `<span class="pill">${escapeHtml(text)}</span>`; }
function escapeHtml(s){ return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])); }

function renderModels(results) {
  $("result-count").textContent = `${results.length} models`;
  $("model-results").innerHTML = results.length ? results.map((r,i)=>`
    <article class="result-card">
      <div class="result-top">
        <div><div class="small">#${i+1} · ${escapeHtml(r.model.reference || "Reference pending")}</div><h3>${escapeHtml(r.model.name)}</h3></div>
        <div class="score">${r.score.toFixed(0)}</div>
      </div>
      <div class="meta">${(r.model.categories||[]).slice(0,4).map(tag).join("")}${tag(r.model.integration)}</div>
      <p class="reason"><strong>Architecture:</strong> ${escapeHtml(r.model.architecture)}</p>
      ${r.reasons.slice(0,4).map(x=>`<p class="reason">✓ ${escapeHtml(x)}</p>`).join("")}
      ${r.cautions.slice(0,3).map(x=>`<p class="caution">△ ${escapeHtml(x)}</p>`).join("")}
      ${r.model.repository ? `<p class="small"><a href="${escapeHtml(r.model.repository)}" target="_blank" rel="noopener">Upstream implementation ↗</a></p>` : ""}
    </article>`).join("") : `<div class="empty">No compatible models passed the hard filters. Relax mesh, dimension, transfer, or memory constraints.</div>`;
}

function renderDatasets(results) {
  $("dataset-results").innerHTML = results.map((r,i)=>`
    <article class="result-card">
      <div class="result-top"><div><div class="small">#${i+1}</div><h3>${escapeHtml(r.dataset.name)}</h3></div><div class="score">${r.score.toFixed(0)}</div></div>
      <p class="reason">${escapeHtml(r.dataset.description)}</p>
      <div class="meta">${(r.dataset.scenarios||[]).slice(0,5).map(tag).join("")}</div>
      ${r.reasons.slice(0,4).map(x=>`<p class="reason">✓ ${escapeHtml(x)}</p>`).join("")}
      ${r.cautions.slice(0,2).map(x=>`<p class="caution">△ ${escapeHtml(x)}</p>`).join("")}
      ${r.dataset.hf_repo_id ? `<p class="small"><a href="https://huggingface.co/datasets/${escapeHtml(r.dataset.hf_repo_id)}" target="_blank" rel="noopener">Open on Hugging Face ↗</a></p>` : ""}
    </article>`).join("");
}

function run() {
  if (!models.length) return;
  const task = taskFromForm();
  const modelResults = recommendModels(task, models, {topK:10});
  const datasetResults = recommendDatasets(task, datasets, {topK:6});
  renderModels(modelResults);
  renderDatasets(datasetResults);
  $("manifest").textContent = JSON.stringify(buildManifest(task, modelResults, datasetResults), null, 2);
}

form.addEventListener("submit", e => {e.preventDefault(); run();});
$("preset").addEventListener("change", e => applyPreset(e.target.value));
$("copy-config").addEventListener("click", async () => {
  await navigator.clipboard.writeText(JSON.stringify(taskFromForm(), null, 2));
  const old = $("copy-config").textContent; $("copy-config").textContent = "Copied";
  setTimeout(()=>$("copy-config").textContent=old,1200);
});
$("reset").addEventListener("click", () => {form.reset(); $("problem").value="cylinder_wake"; $("memory").value=24; run();});

document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{
  document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active")); btn.classList.add("active");
  for (const name of ["models","datasets","config"]) $(`${name}-tab`).classList.toggle("hidden", name!==btn.dataset.tab);
}));

run();
